AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  thumbnail-app

  Sample SAM Template for thumbnail-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: thumbnail-new-bucket
  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"
  thumbnailstepwithsam:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "A description of my state machine",
              "StartAt": "Thumbnail Function",
              "States": {
                "Thumbnail Function": {
                  "Type": "Task",
                  "Resource": "arn:aws:states:::lambda:invoke",
                  "OutputPath": "$.Payload",
                  "Parameters": {
                    "Payload.$": "$",
                    "FunctionName": "arn:aws:lambda:us-east-1:960351580303:function:thumbnail-app-ThumbnailFunction-ACek6Mcu29DH:$LATEST"
                  },
                  "Retry": [
                    {
                      "ErrorEquals": [
                        "Lambda.ServiceException",
                        "Lambda.AWSLambdaException",
                        "Lambda.SdkClientException",
                        "Lambda.TooManyRequestsException"
                      ],
                      "IntervalSeconds": 1,
                      "MaxAttempts": 3,
                      "BackoffRate": 2
                    }
                  ],
                  "Next": "Metadata Function"
                },
                "Metadata Function": {
                  "Type": "Task",
                  "Resource": "arn:aws:states:::lambda:invoke",
                  "OutputPath": "$.Payload",
                  "Parameters": {
                    "Payload.$": "$",
                    "FunctionName": "arn:aws:lambda:us-east-1:960351580303:function:thumbnail-app-MetaDataFunction-bGYsvq08Y4TM:$LATEST"
                  },
                  "Retry": [
                    {
                      "ErrorEquals": [
                        "Lambda.ServiceException",
                        "Lambda.AWSLambdaException",
                        "Lambda.SdkClientException",
                        "Lambda.TooManyRequestsException"
                      ],
                      "IntervalSeconds": 1,
                      "MaxAttempts": 3,
                      "BackoffRate": 2
                    }
                  ],
                  "End": true
                }
              }
            }
          - {ThumbnailFunctionArn: !GetAtt [ ThumbnailFunction , Arn ],MetaDataFunctionArn : !GetAtt [ MetaDataFunction , Arn]}
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]
  SecondBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: thumbnail-new-second-bucket
  MetaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName : filename
          AttributeType : S 
      KeySchema:
        - AttributeName : filename
          KeyType :  HASH
      ProvisionedThroughput:
        ReadCapacityUnits :  5
        WriteCapacityUnits : 5
      StreamSpecification:
        StreamViewType :  NEW_IMAGE
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref Bucket 
        - S3CrudPolicy:
            BucketName: !Ref SecondBucket
      Environment:
        Variables:
          bucket_name: !Ref Bucket
          second_bucket_name: !Ref SecondBucket
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: post
  ThumbnailFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.thumbnail_generator
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref Bucket 
        - S3CrudPolicy:
            BucketName: !Ref SecondBucket
        - DynamoDBCrudPolicy:
            TableName : !Ref MetaTable
      Environment:
        Variables:
          bucket_name: !Ref Bucket
          second_bucket_name: !Ref SecondBucket
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /generate
            Method: post
  MetaDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.metadata_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName : !Ref MetaTable  
      Environment:
        Variables:
          bucket_name: !Ref Bucket
          second_bucket_name: !Ref SecondBucket
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /metadat
            Method: post
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  
